spring:
  config:
    activate:
      on-profile: justin
  main:
    lazy-initialization: false
  # setup profiles
  profiles:
    active: project
  # setup banner.txt
  banner:
    location: classpath:banner.txt.txt
    image:
      location: classpath:baniere.png
      height: 10
      width: 20
  # database setup - possible de faire appel au prop du pom.xml : ${prop}
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# custom properties
custom:
  name: Francois Vandermersch, Martin Pierret
  lastName: and Justin Carroll