spring:
  # lazy init
  main:
    lazy-initialization: false
  # setup profiles
  profiles:
    active: project
  # setup banner.txt
  banner:
    location: classpath:banner.txt.txt
    image:
      location: classpath:baniere.png
      height: 10
      width: 20
  # database setup - possible de faire appel au prop du pom.xml : ${prop}
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:memDB
    username: root
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false

# custom properties
custom:
  name: Francois Vandermersch, Martin Pierret
  lastName: and Justin Carroll